version: '3'
services:
  postgres:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=Zaq12wsx'
      - 'POSTGRES_DB=kanban-site'