version: '3'
services:
  database:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=${TYPEORM_USERNAME}'
      - 'POSTGRES_PASSWORD=${TYPEORM_PASSWORD}'
      - 'POSTGRES_DB=${TYPEORM_DATABASE}'
  cache:
    image: 'redis'
    ports:
      - '6379:6379'
