version: '3'
services:
  database:
    image: 'postgres'
    ports:
      - '${TYPEORM_PORT}:5432'
    environment:
      - 'POSTGRES_USER=${TYPEORM_USERNAME}'
      - 'POSTGRES_PASSWORD=${TYPEORM_PASSWORD}'
      - 'POSTGRES_DB=${TYPEORM_DATABASE}'
